version: 0.2

phases:
  install:
    commands:
      - echo "Installing Software..."
      - yum update -y
      - yum install -y docker
      - service docker start
      - docker --version  # Verify Docker installation 
      - echo "Software Installed..."
      
  pre_build: 
    commands: 
      - echo "Logging in to Amazon ECR...."
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 123159274940.dkr.ecr.eu-north-1.amazonaws.com
      
  build:
    commands:
      - echo "Building Docker image..."
      - mvn clean install
      - docker build -t videopivcuat .
      - docker tag videopivcuat:latest 123159274940.dkr.ecr.eu-north-1.amazonaws.com/demo-test
      
  post_build:
    commands:
      - echo "Pushing Docker image to Amazon ECR..."
      - docker push 123159274940.dkr.ecr.eu-north-1.amazonaws.com/demo-test
